<?php
//	echo 'Zde budou dokumenty pro vybraného člena týmu';
	echo <<<EOT
 <table class="header-table">
 <tr><td><ul>
	    <li>Kontrakt</li>
	    <li>Procent</li>
	    <li>Očekávání</li>
	    <li class="scroll"></li>
	  </ul></td></tr>
 </table>
 <table class="provisions-table">
	  <tr><td><ul>
	    <li>123456-1234567890/1234</li>
	    <li>100%</li>
	    <li>20.000,-</li>
	  </ul></td></tr>
	  <tr><td><ul>
	    <li>789456</li>
	    <li>50%</li>
	    <li>6.400,-</li>
	  </ul></td></tr>
	  <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	  <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
    	<tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
	    <tr><td><ul>
	    <li>DEMO</li>
	    <li>0%</li>
	    <li>0,-</li>
	  </ul></td></tr>
  </table> 
EOT
?>
	